routes/web.php
<?php

use App\Http\Controllers\Backend\AdminController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ClientController;
use App\Http\Controllers\Backend\PortofolioCategoryController;
// use App\Http\Controllers\ContactController;
use App\Http\Controllers\Backend\PortofolioController;
use App\Http\Controllers\Backend\PostController;
use App\Http\Controllers\Backend\ProductCategoryController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ProductTagController;
use App\Http\Controllers\Backend\SettingsController;
use App\Http\Controllers\Backend\TagController;
use App\Http\Controllers\Backend\TeamController;
use App\Http\Controllers\Backend\TestimonialController;
use App\Http\Controllers\Backend\UsersController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\RssController;
use App\Http\Controllers\SearchesController;

Route::get('/home', [HomeController::class,'index']);
Auth::routes();
//backend admin
Route::group(['prefix' => 'admin', 'as' => 'backend.', 'middleware' => ['auth']], function () {
    Route::get('/', [AdminController::class, 'index']);
    Route::resource('users', UsersController::class);
    // Route::resource('maps', );
    Route::resource('post', PostController::class);
    Route::resource('post_categories', CategoryController::class);
    Route::resource('post_tags', TagController::class);
    Route::resource('portofolio_categories', PortofolioCategoryController::class);
    Route::resource('portofolio', PortofolioController::class);
    Route::resource('product_categories', ProductCategoryController::class);
    // Route::match(['get','post'],'product-attribute/{id}','Backend\ProductController@addAttribute');
    Route::resource('product', ProductController::class);
    Route::resource('product_tag', ProductTagController::class);
    Route::resource('testimonial', TestimonialController::class);
    Route::resource('client_categories', ClientCategoryController::class);
    Route::resource('client', ClientController::class);
    Route::resource('team', TeamController::class);
    Route::resource('team_division', DivisionController::class);
    Route::get(
        '/settings',
        array('as' => 'settings.index', 'uses' => [SettingsController::class, 'profile'])
    );
    Route::post(
        '/settings',
        array('as' => 'settings.profile',
            'uses' => [SettingsController::class, 'UpdateProfile'])
    );
});

//frontend
Route::group(['prefix' => '/', 'as' => 'front.'], function () {
    Route::get('/', [FrontController::class, 'index']);
    Route::get('blog', [FrontController::class, 'blog']);
    Route::get('blog/tag/{tag}', array('as' => 'blogtag', 'uses' => [FrontController::class, 'blogtag']));
    Route::get('blog/category/{category}', array('as' => 'blogcategory', 'uses' => [FrontController::class, 'blogcategory']));
    Route::get('blog/{blog}', array('as' => 'singleblog', 'uses' => [FrontController::class, 'singleblog']));
    // Route::resource('contact', 'ContactController');
    Route::resource('contact', ContactController::class);
    Route::get('about', [FrontController::class, 'about']);
    Route::get('product', [FrontController::class, 'product']);
    Route::get('product/{product}', [FrontController::class, 'singleproduct'])->name('singleproduct');
    Route::get('testimonial', [FrontController::class, 'testimonial']);
    Route::get('portofolio', [FrontController::class, 'portofolio']);
    Route::get('client', [FrontController::class, 'client']);
    Route::get('service', [FrontController::class, 'service']);
    Route::get('search', [SearchesController::class, 'search']);
    Route::get('/rss', [RssController::class, 'rss']);
    // cart
    Route::get('cart', [CartController::class, 'index']);
    Route::post('cart', [
        'as' => 'cart',
        'uses' => [CartController::class, 'addTocart'],
    ]);
    Route::delete('cart/{id}', [
        'as' => 'cart.delete',
        'uses' => [CartController::class, 'delete'],
    ]);

    Route::get('cart/update/{cart}', [
        'as' => 'cart.update',
        'uses' => [CartController::class, 'updateCart'],
    ]);

    Route::get('checkout', [
        'as' => 'checkout',
        'uses' => [CartController::class, 'checkout'],
    ]);
});

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

class AdminController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Alert;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Str;
use Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $categories = Category::latest()->paginate(12);
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|max:255|unique:categories',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
            'name.unique' => 'Category is already used find another category',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $categories = new Category;
        $categories->name = $request->name;
        $categories->slug = Str::slug($request->name, '-');
        $categories->save();
        Alert::success('Data successfully saved', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.post_categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|max:255',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $categories = Category::findOrFail($id);
        $categories->name = $request->name;
        $categories->slug = Str::slug($request->name, '-');
        $categories->save();
        Alert::success('Data successfully edited', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.post_categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!Category::destroy($id)) {
            Alert::error('Category can not be deleted because it still has post!', 'Oops!')->persistent("Ok");
            return redirect()->back();
        } else {
            Alert::success('Data successfully deleted', 'Good Job')->autoclose(1500);
        }
        return back();
    }
}

app/Http/Controllers/Backend/ClientCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Alert;
use App\Http\Controllers\Controller;
use App\Models\ClientCategory;
use Illuminate\Http\Request;
use Str;
use Validator;

class ClientCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $clientcategories = ClientCategory::latest()->paginate(12);
        return view('backend.client_category.index', compact('clientcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|max:255|unique:client_categories',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
            'name.unique' => 'Category is already used find another category',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $clientcategories = new clientCategory;
        $clientcategories->name = $request->name;
        $clientcategories->slug = Str::slug($request->name, '-');
        $clientcategories->save();
        Alert::success('Data successfully saved', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.client_categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|max:255',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $clientcategories = clientCategory::findOrFail($id);
        $clientcategories->name = $request->name;
        $clientcategories->slug = Str::slug($request->name, '-');
        $clientcategories->save();
        Alert::success('Data successfully edited', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.client_categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        clientCategory::findOrFail($id)->delete();
        Alert::success('Data successfully deleted', 'Good Job')->autoclose(1500);
        return back();
    }
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Validator;
use Alert;
use Mail;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.contact');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $input = $request->only('name', 'email', 'pesan','phone');

        $rules = array(
          'name' => 'required|max:40',
          'email' => 'required|email',
          'phone' => 'required',
          'pesan' => 'required|min:10|max:300',
          'g-recaptcha-response' => 'required|captcha',);

         $pesan = array(
            'name.required' => 'Your Name should not be empty',
            'email.required' => 'Your Email should not be empty',
            'pesan.required' => 'Your Message should not be empty',
            'pesan.min' => 'Your message can not be less than 10 characters',
            'pesan.max' => 'your message can not be more than 300 characters',
            'phone.required' => 'Your Phone should not be empty',);

        $validation = Validator::make($request->all(), $rules, $pesan);
        if ($validation->fails())
        {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        } else {
            Mail::send('emails.contact', $input, function($message) use ($input)
                {
            //email 'From' field: Get users email add and name
                $message->from($input['email'] , $input['name']);
            //email 'To' field: cahnge this to emails that you want to be notified.                    
                $message->to('candraherdiansyah14@gmail.com', 'candra')->cc('candraherdiansyah14@gmail.com')->subject('contact request');
                });
            Alert::success('Thanks for contacting us!','Good Job')->autoclose(1500);
            return Redirect ('contact');
    }
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/SettingsController.php
<?php

namespace App\Http\Controllers\Backend;

use Alert;
use App\Http\Controllers\Controller;
use Auth;
use Illuminate\Http\Request;
use Session;

class SettingsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function profile()
    {
        return view('backend.settings.index');
    }
    public function UpdateProfile(Request $request)
    {
        $user = Auth::user();
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users,email,' . $user->id,
            'password' => 'required|passcheck:' . $user->password,
            'new_password' => 'required|confirmed|min:6',
        ], [
            'password.passcheck' => 'Password lama tidak sesuai',
        ]);

        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->password = bcrypt($request->get('new_password'));
        $user->save();
        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Profil berhasil diubah",
        ]);
        Alert::success('Data successfully saved', 'Good Job')->autoclose(2000);
        return redirect()->route('backend.settings.index');
    }
}

resources/views/partials/backend/navbar.blade.php
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner ">
        <div class="page-logo">
            <a href="{{ url('admin') }}">
                <img src="{!!asset('/assets/backend/logo.png')!!}" alt="logo" class="logo-default" width="175" height="50" /> </a>
            <div class="menu-toggler sidebar-toggler">
            </div>
        </div>
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        <div class="page-top">
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown dropdown-user dropdown-dark">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <span class="username username-hide-on-mobile">{{ Auth::user()->name }} </span>
                            <img alt="" class="img-circle" src="/assets/backend/layouts/layout4/img/avatar.png" /> </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="{{ route('backend.settings.index') }}">
                                    <i class="icon-user"></i> My Profile </a>
                            </li>
                            <li class="divider"> </li>
                            <li>
                                <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    <i class="icon-key"></i> Log Out </a>
                            </li>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/partials/backend/sidebar.blade.php
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <li class="nav-item start {{ Request::is('admin') ? 'active open' : '' }}">
                <a href="{{ url('/admin') }}" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="heading">
                <h3 class="uppercase">Features</h3>
            </li>
            @if (Auth::user()->permission === 'Admin')
                <li class="nav-item  {{ Request::is('admin/users*') ? 'active open' : '' }}">
                    <a href="{{ route('backend.users.index') }}" class="nav-link nav-toggle">
                        <i class="icon-users"></i>
                        <span class="title">Manajemen User</span>
                        {{-- <span class="arrow"></span> --}}
                    </a>
                </li>
            @endif
            <li class="nav-item {{ Request::is('admin/post*') ? 'active open' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-puzzle"></i>
                    <span class="title">Blog</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  {{ Request::is('admin/post') ? 'active open' : '' }}">
                        <a href="{{ route('backend.post.index') }}" class="nav-link">
                            <span class="title">Daftar Blog</span>
                            <span class="badge badge-success">{{ count($post) }}</span>
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/post_categories') ? 'active open' : '' }}">
                        <a href="{{ route('backend.post_categories.index') }}" class="nav-link">
                            <span class="title">Kategori</span>
                            <span class="badge badge-warning">{{ count($category) }}</span>
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/post_tags') ? 'active open' : '' }}">
                        <a href="{{ route('backend.post_tags.index') }}" class="nav-link">
                            <span class="title">Tag</span>
                            {{-- <span class="badge badge-danger">{{ count($tag) }}</span> --}}
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  {{ Request::is('admin/product*') ? 'active open' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-briefcase"></i>
                    <span class="title">Produk</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  {{ Request::is('admin/product') ? 'active open' : '' }}">
                        <a href="{{ route('backend.product.index') }}" class="nav-link">
                            <span class="title">Daftar Produk</span>
                            <span class="badge badge-success">{{ count($product) }}</span>
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/product_categories') ? 'active open' : '' }}">
                        <a href="{{ route('backend.product_categories.index') }}" class="nav-link">
                            <span class="title">Kategori Produk</span>
                            <span class="badge badge-warning">{{ count($product_categories) }}</span>
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/product_tag') ? 'active open' : '' }}">
                        <a href="{{ route('backend.product_tag.index') }}" class="nav-link">
                            <span class="title">Tag Produk</span>
                            <span class="badge badge-danger">{{ count($product_tag) }}</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  {{ Request::is('admin/portofolio*') ? 'active open' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-tag"></i>
                    <span class="title">Portofolio</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  {{ Request::is('admin/portofolio') ? 'active open' : '' }}">
                        <a href="{{ route('backend.portofolio.index') }}" class="nav-link">
                            <span class="title">Daftar Portofolio</span>
                            <span class="badge badge-success">{{ count($portofolio) }}</span>
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/portofolio_categories') ? 'active open' : '' }}">
                        <a href="{{ route('backend.portofolio_categories.index') }}" class="nav-link">
                            <span class="title">Kategori</span>
                            <span class="badge badge-warning">{{ count($portofoliocategories) }}</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  {{ Request::is('admin/client*') ? 'active open' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-wallet"></i>
                    <span class="title">Klien</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  {{ Request::is('admin/client') ? 'active' : '' }}">
                        <a href="{{ route('backend.client.index') }}" class="nav-link">
                            <span class="title">Daftar Klien</span>
                            <span class="badge badge-success">{{ count($client) }}</span>
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/client_categories') ? 'active open' : '' }}">
                        <a href="{{ route('backend.client_categories.index') }}" class="nav-link">
                            <span class="title">Category</span>
                            <span class="badge badge-warning">{{ count($client_categories) }}</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  {{ Request::is('admin/team*') ? 'active open' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-bulb"></i>
                    <span class="title">Tim Assalaam Studio</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item  {{ Request::is('admin/team') ? 'active' : '' }}">
                        <a href="{{ route('backend.team.index') }}" class="nav-link">
                            <span class="title">Daftar Tim</span>
                            <span class="badge badge-success">{{ count($team) }}</span>
                        </a>
                    </li>
                    <li class="nav-item  {{ Request::is('admin/team_division') ? 'active open' : '' }}">
                        <a href="{{ route('backend.team_division.index') }}" class="nav-link">
                            <span class="title">Divisi Kerja</span>
                            <span class="badge badge-warning">{{ count($division) }}</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item  {{ Request::is('admin/testimonial') ? 'active open' : '' }}">
                <a href="{{ url('/admin/testimonial') }}" class="nav-link nav-toggle">
                    <i class="icon-social-dribbble"></i>
                    <span class="title">Testmonial</span>
                    {{-- <span class="arrow"></span> --}}
                </a>
            </li>
        </ul>
    </div>
</div>