routes/web.php
<?php

use App\Http\Controllers\Backend\AdminController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\ClientController;
use App\Http\Controllers\Backend\PortofolioCategoryController;
// use App\Http\Controllers\ContactController;
use App\Http\Controllers\Backend\PortofolioController;
use App\Http\Controllers\Backend\PostController;
use App\Http\Controllers\Backend\ProductCategoryController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ProductTagController;
use App\Http\Controllers\Backend\SettingsController;
use App\Http\Controllers\Backend\TagController;
use App\Http\Controllers\Backend\TeamController;
use App\Http\Controllers\Backend\TestimonialController;
use App\Http\Controllers\Backend\UsersController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\RssController;
use App\Http\Controllers\SearchesController;

Route::get('/home', [HomeController::class,'index']);
Auth::routes();
//backend admin
Route::group(['prefix' => 'admin', 'as' => 'backend.', 'middleware' => ['auth']], function () {
    Route::get('/', [AdminController::class, 'index']);
    Route::resource('users', UsersController::class);
    // Route::resource('maps', );
    Route::resource('post', PostController::class);
    Route::resource('post_categories', CategoryController::class);
    Route::resource('post_tags', TagController::class);
    Route::resource('portofolio_categories', PortofolioCategoryController::class);
    Route::resource('portofolio', PortofolioController::class);
    Route::resource('product_categories', ProductCategoryController::class);
    // Route::match(['get','post'],'product-attribute/{id}','Backend\ProductController@addAttribute');
    Route::resource('product', ProductController::class);
    Route::resource('product_tag', ProductTagController::class);
    Route::resource('testimonial', TestimonialController::class);
    Route::resource('client_categories', ClientCategoryController::class);
    Route::resource('client', ClientController::class);
    Route::resource('team', TeamController::class);
    Route::resource('team_division', DivisionController::class);
    Route::get(
        '/settings',
        array('as' => 'settings.index', 'uses' => [SettingsController::class, 'profile'])
    );
    Route::post(
        '/settings',
        array('as' => 'settings.profile',
            'uses' => [SettingsController::class, 'UpdateProfile'])
    );
});

//frontend
Route::group(['prefix' => '/', 'as' => 'front.'], function () {
    Route::get('/', [FrontController::class, 'index']);
    Route::get('blog', [FrontController::class, 'blog']);
    Route::get('blog/tag/{tag}', array('as' => 'blogtag', 'uses' => [FrontController::class, 'blogtag']));
    Route::get('blog/category/{category}', array('as' => 'blogcategory', 'uses' => [FrontController::class, 'blogcategory']));
    Route::get('blog/{blog}', array('as' => 'singleblog', 'uses' => [FrontController::class, 'singleblog']));
    // Route::resource('contact', 'ContactController');
    Route::resource('contact', ContactController::class);
    Route::get('about', [FrontController::class, 'about']);
    Route::get('product', [FrontController::class, 'product']);
    Route::get('product/{product}', [FrontController::class, 'singleproduct'])->name('singleproduct');
    Route::get('testimonial', [FrontController::class, 'testimonial']);
    Route::get('portofolio', [FrontController::class, 'portofolio']);
    Route::get('client', [FrontController::class, 'client']);
    Route::get('service', [FrontController::class, 'service']);
    Route::get('search', [SearchesController::class, 'search']);
    Route::get('/rss', [RssController::class, 'rss']);
    // cart
    Route::get('cart', [CartController::class, 'index']);
    Route::post('cart', [
        'as' => 'cart',
        'uses' => [CartController::class, 'addTocart'],
    ]);
    Route::delete('cart/{id}', [
        'as' => 'cart.delete',
        'uses' => [CartController::class, 'delete'],
    ]);

    Route::get('cart/update/{cart}', [
        'as' => 'cart.update',
        'uses' => [CartController::class, 'updateCart'],
    ]);

    Route::get('checkout', [
        'as' => 'checkout',
        'uses' => [CartController::class, 'checkout'],
    ]);
});

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

class AdminController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Alert;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Str;
use Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $categories = Category::latest()->paginate(12);
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|max:255|unique:categories',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
            'name.unique' => 'Category is already used find another category',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $categories = new Category;
        $categories->name = $request->name;
        $categories->slug = Str::slug($request->name, '-');
        $categories->save();
        Alert::success('Data successfully saved', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.post_categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|max:255',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $categories = Category::findOrFail($id);
        $categories->name = $request->name;
        $categories->slug = Str::slug($request->name, '-');
        $categories->save();
        Alert::success('Data successfully edited', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.post_categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!Category::destroy($id)) {
            Alert::error('Category can not be deleted because it still has post!', 'Oops!')->persistent("Ok");
            return redirect()->back();
        } else {
            Alert::success('Data successfully deleted', 'Good Job')->autoclose(1500);
        }
        return back();
    }
}

app/Http/Controllers/Backend/ClientCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Alert;
use App\Http\Controllers\Controller;
use App\Models\ClientCategory;
use Illuminate\Http\Request;
use Str;
use Validator;

class ClientCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $clientcategories = ClientCategory::latest()->paginate(12);
        return view('backend.client_category.index', compact('clientcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|max:255|unique:client_categories',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
            'name.unique' => 'Category is already used find another category',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $clientcategories = new clientCategory;
        $clientcategories->name = $request->name;
        $clientcategories->slug = Str::slug($request->name, '-');
        $clientcategories->save();
        Alert::success('Data successfully saved', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.client_categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|max:255',
        ];

        $message = [
            'name.required' => 'The Name Category is required',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails()) {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }
        $clientcategories = clientCategory::findOrFail($id);
        $clientcategories->name = $request->name;
        $clientcategories->slug = Str::slug($request->name, '-');
        $clientcategories->save();
        Alert::success('Data successfully edited', 'Good Job')->autoclose(1500);
        return redirect()->route('backend.client_categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        clientCategory::findOrFail($id)->delete();
        Alert::success('Data successfully deleted', 'Good Job')->autoclose(1500);
        return back();
    }
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Validator;
use Alert;
use Mail;
class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.contact');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $input = $request->only('name', 'email', 'pesan','phone');

        $rules = array(
          'name' => 'required|max:40',
          'email' => 'required|email',
          'phone' => 'required',
          'pesan' => 'required|min:10|max:300',
          'g-recaptcha-response' => 'required|captcha',);

         $pesan = array(
            'name.required' => 'Your Name should not be empty',
            'email.required' => 'Your Email should not be empty',
            'pesan.required' => 'Your Message should not be empty',
            'pesan.min' => 'Your message can not be less than 10 characters',
            'pesan.max' => 'your message can not be more than 300 characters',
            'phone.required' => 'Your Phone should not be empty',);

        $validation = Validator::make($request->all(), $rules, $pesan);
        if ($validation->fails())
        {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        } else {
            Mail::send('emails.contact', $input, function($message) use ($input)
                {
            //email 'From' field: Get users email add and name
                $message->from($input['email'] , $input['name']);
            //email 'To' field: cahnge this to emails that you want to be notified.                    
                $message->to('candraherdiansyah14@gmail.com', 'candra')->cc('candraherdiansyah14@gmail.com')->subject('contact request');
                });
            Alert::success('Thanks for contacting us!','Good Job')->autoclose(1500);
            return Redirect ('contact');
    }
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/SettingsController.php
<?php

namespace App\Http\Controllers\Backend;

use Alert;
use App\Http\Controllers\Controller;
use Auth;
use Illuminate\Http\Request;
use Session;

class SettingsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function profile()
    {
        return view('backend.settings.index');
    }
    public function UpdateProfile(Request $request)
    {
        $user = Auth::user();
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users,email,' . $user->id,
            'password' => 'required|passcheck:' . $user->password,
            'new_password' => 'required|confirmed|min:6',
        ], [
            'password.passcheck' => 'Password lama tidak sesuai',
        ]);

        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->password = bcrypt($request->get('new_password'));
        $user->save();
        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Profil berhasil diubah",
        ]);
        Alert::success('Data successfully saved', 'Good Job')->autoclose(2000);
        return redirect()->route('backend.settings.index');
    }
}

resources/views/backend/product_category/_modal-add.blade.php
<div class="modal fade bs-modal-lg" id="tambah" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <form action="{{ route('backend.product_categories.store') }}"  method="post">
        {{ csrf_field() }}
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-laptop"></i> Add Data</h4>
            </div>
            <div class="modal-body">
             <div class="portlet-body">
                    
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label class="control-label">Category Name</label>
            <div class="col-md-12">
               <input type="text" class="form-control" name="name" placeholder="Category" required>
               </input>
               @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        </div>
        </div>
            
            <div class="modal-footer">
                <button type="button" class="btn blue btn-outline" data-dismiss="modal">Close</button>
                <button type="submit" class="btn green">Save changes</button>
            </div>
        </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/backend/product_category/_modal-edit.blade.php
<div class="modal fade bs-modal-lg" id="edit{{ $data->id }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <form action="{{ route('backend.product_categories.update',$data->id) }}"  method="post">
        <input name="_method" type="hidden" value="PATCH">
        {{ csrf_field() }}
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-laptop"></i> Edit Data</h4>
            </div>
            <div class="modal-body">
             <div class="portlet-body">
                    
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label class="control-label ">Tag Name</label>
            <div class="col-md-12">
               <input type="text" class="form-control fa fa-file fileinput-exists" placeholder="Category" name="name" required value="{{ $data->name }}">
               </input>
               @if ($errors->has('name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        </div>
        </div>
            
            <div class="modal-footer">
                <button type="button" class="btn blue btn-outline" data-dismiss="modal">Close</button>
                <button type="submit" class="btn green">Save changes</button>
            </div>
        </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/backend/product_category/index.blade.php
@extends('layouts.backend')
@section('css')
@endsection

@section('js')
@endsection

@section('title')
<i class="icon-settings"></i> <span class="title">Product Management</span>
@endsection
@section('subtitle')
<i class="icon-settings"></i>
@endsection

@section('content')
<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-bubble font-green-sharp"></i>
            <span class="caption-subject font-green-sharp sbold">Product Category</span>
        </div>
       <div class="actions">
            <a class="btn purple btn btn-circle sbold" data-toggle="modal" href="#tambah">  <i class="fa fa-plus"></i> Add </a>
            <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;"> </a>
        </div>
        {{-- Modal Tambah --}}
        @include('backend.product_category._modal-add')
        {{-- End Modal --}}
    </div>
    {{-- Table --}}
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th> No </th>
                    <th> Name </th>
                    <th> Slug </th>
                    <th colspan="3"> Action </th>
                </tr>
            </thead>
            <tbody>
            @php $no=1; @endphp
            @foreach($productcategories as $data)
                <tr>
                    <td> {{ $no++ }} </td>
                    <td> {{ $data->name }} </td>
                    <td> {{ $data->slug }} </td>
                    <td><a class="btn yellow btn btn-circle sbold" data-toggle="modal" href="#edit{{$data->id}}">  <i class="fa fa-pencil"></i> Edit </a>
                    </td>
                    <td>
                        {!! Form::model($data, ['route' => ['backend.product_categories.destroy', $data->id], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                        {!! Form::button('<i class="fa fa-trash">  Delete </i>', ['type' => 'submit','class'=>'btn red btn btn-circle sbold js-submit-confirm'])!!}
                        {!! Form::close()!!}
                    </td>
                    <td></td>
                </tr>
                {{-- Edit Modal --}}
                 @include('backend.product_category._modal-edit')
                {{-- End Edit Modal --}}
            @endforeach
            </tbody>
        </table>
        <center>{{ $productcategories->links() }}</center>
    </div>
    {{-- End Table --}}
</div>

@push('scripts')
@endpush
@endsection